version: '3'
services:
    nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/www/:/var/www/certbot/:ro
      ports:
        - 80:80
        - 443:443
      networks:
        - custom-net
    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
      networks:
        - custom-net
    hello-world:
      image: lmmendes/http-hello-world
      container_name: hello-world
      restart: unless-stopped
      ports:
        - 8888:80
      networks:
        - custom-net
networks:
  custom-net:
    external: true